version: '3.2'
services:
  mongo:
    image: mongo:4.2
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  rabbitmq:
      image: rabbitmq:3.8.0-management-alpine
      ports:
        - 15672:15672
        - 5672:5672
      healthcheck:
        test: rabbitmq-diagnostics -q check_port_connectivity && rabbitmq-diagnostics -q node_health_check || exit 1
        interval: 20s
        timeout: 10s
        retries: 5
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - "5001:443"
      - "8001:80"
    environment:
      DBConnectionString: mongodb://admin:password@boardsdb
      DBName: kibindb_mongo
      ClientID: e20f75e27d4e896699ff7dc85f3521f1e6e40d7741201bf5c1138fa4c28c270f
      ClientSecret: b4e4fb4988915f351ac784a489adb083a38c8ac0a9e0b7a56d287a5b88b50f99
      ClientURL: http://proflo.app.cgi-w3.stackroute.io
      CallbackURL: http://proflo.app.cgi-w3.stackroute.io/boards/api/auth/callback
      RabbitMQURL: rabbitmq
    links:
      - "mongo:database"
    depends_on:
      - mongo
      - rabbitmq
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: client
    ports: 
      - "4200:80"
    volumes:
      - ./client/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  mongodb_data:
    driver: local
  