apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: boardsclaim
 namespace: proflo
spec:
 accessModes:
   - ReadWriteOnce
 volumeMode: Filesystem
 storageClassName: gp2
 resources:
   requests:
     storage: 5Gi
